/* Generated by AN DISI Unibo */ 
package it.unibo.sender_0;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sender_0 extends QActorMsgQueue{
	public MsgHandle_Sender_0(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
