/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.receiver;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Receiver extends AbstractReceiver { 
	public Receiver(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
