/* Generated by AN DISI Unibo */
/*
This code is generated only ONCE
*/
package it.unibo.client;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Client extends AbstractClient {
	public Client(String actorId, QActorContext myCtx, IOutputEnvView outEnvView) throws Exception {
		super(actorId, myCtx, outEnvView);
	}

	public void submitJob(String jobSourceCodeFilePath) {
		String workerUrl = "http://localhost:3000";
		sendPostRequest(workerUrl, jobSourceCodeFilePath);
	}

	private void sendPostRequest(String receiverUrl, String bodyFilePath) {

		List<String> allBodyLines = null;
		HttpURLConnection con = null;
		try {
			// Read body from file
			Path bodyFilePathObj = Paths.get(bodyFilePath);
			allBodyLines = Files.readAllLines(bodyFilePathObj);

			// Open a connection to the destination
			URL recipientURLObj = new URL(receiverUrl);
			con = (HttpURLConnection) recipientURLObj.openConnection();

			// Configure the request
			con.setRequestMethod("POST");
			con.setDoOutput(true);
		} catch (IOException e) {
			e.printStackTrace();
		}

		OutputStreamWriter wr = null;
		try {
			wr = new OutputStreamWriter(con.getOutputStream());

			// Send post request
			for (String currentLine : allBodyLines) {
				wr.write(currentLine + "\n");
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				wr.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}

		try {
			System.out.println(con.getResponseMessage());
		} catch (IOException e) {
			e.printStackTrace();
		}
		con.disconnect();
	}

}
