/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.job_launcher;
import java.io.IOException;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Job_launcher extends AbstractJob_launcher { 
	public Job_launcher(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void launchJob(String pathToJobSourceCodeFile) {
        try {
            Runtime.getRuntime().exec("node " + pathToJobSourceCodeFile);
        } catch (IOException e) {
            e.printStackTrace();
        }
	}
}
